services:
  - type: web
    name: plutusai-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CONTACT_EMAIL
        sync: false
      
  - type: worker
    name: plutusai-discord
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python discord_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: DISCORD_GUILD_ID
        sync: false
      - key: DISCORD_CHANNEL_ID
        sync: false
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: API_URL
        value: https://plutusai-api.onrender.com # This will be your API service URL 